CFLAG = -std=c++11 -Wall -g
all: run-c++.exe 

run-c++: LongestIncreasingSubsequence.h main.cpp
	     g++ $(CFLAG) main.cpp -o run-c++
	     @echo "--------- test for c++ ----------"
	     ./run-c++.exe







