CFLAG = -std=c++11 -Wall -g
all: run-c++.exe 

run-c++.exe: HouseRobber3.h main.cpp
	     g++ $(CFLAG) main.cpp -o run-c++.exe
	     @echo "--------- test for c++ ----------"
	     ./run-c++.exe







